name: HA Cluster Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-ha-cluster:
    runs-on: ubuntu-latest
    env:
      STATIC_IP: 192.168.1.100
      SUBNET_MASK: 255.255.255.0
      GATEWAY: 192.168.1.1
      DNS_SERVERS: 8.8.8.8,8.8.4.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make setup script executable
        run: chmod +x ha_cluster_setup.sh

      - name: Run HA Cluster Setup Script
        run: |
          export STATIC_IP="${STATIC_IP}"
          export SUBNET_MASK="${SUBNET_MASK}"
          export GATEWAY="${GATEWAY}"
          export DNS_SERVERS="${DNS_SERVERS}"
          sudo ./ha_cluster_setup.sh
