# hacluster.yml
# Contextualized for HArmadillium HA setup
# Edit node hostnames/IPs and resources as needed

cluster_name: HArmadilliumCluster

nodes:
  - name: node1
    address: 192.168.1.100
  - name: node2
    address: 192.168.1.101

corosync:
  transport: udp
  mcastaddr: 239.255.42.42
  mcastport: 5405
  authkey: /etc/corosync/authkey
  interface: eth0

pacemaker:
  stonith-enabled: false
  no-quorum-policy: ignore

resources:
  - id: ClusterIP
    type: ocf:heartbeat:IPaddr2
    params:
      ip: 192.168.1.200
      cidr_netmask: 24
      nic: eth0
  - id: nginx
    type: systemd:nginx
    operations:
      - name: start
        interval: 0
      - name: stop
        interval: 0
      - name: monitor
        interval: 30s

constraints:
  colocation:
    - resource_set:
        - ClusterIP
        - nginx
      score: INFINITY
  order:
    - before: ClusterIP
      after: nginx

# fencing:
#   devices:
#     - id: my_fence
#       agent: fence_ipmilan
#       params:
#         ipaddr: 192.168.1.201
#         login: admin
#         passwd: secret
